spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: 'true'
        default_schema: videotecha
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videotecha}
  flyway:
    url: jdbc:postgresql://localhost:5432/videotecha
    schemas: videotecha
    user: postgres
    password: postgres
